import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./../styles/globals.css";
import { Providers } from "@/features/shared/providers/providers";

const inter = Inter({
  variable: "--font-sans",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Planor",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col font-sans">
        <Providers>
        {children}
        </Providers>
        </body>
    </html>
  );
}